version: '0.0.1'
namespace: 'default'
feature_flags:
  - name: 'my-feature-flag-1'
    labels:
      - 'team=A'
      - 'team=B'

subgraphs:
  - name: 'employees'
    schema_path: 'demos/go/pkg/subgraphs/employees/subgraph/schema.graphqls'
    routing_url: 'https://employees-default-${PR_NUMBER}.fly.dev/graphql'

  - name: 'family'
    schema_path: 'demos/go/pkg/subgraphs/family/subgraph/schema.graphqls'
    routing_url: 'https://family-default-${PR_NUMBER}.fly.dev/graphql'

  - name: 'products'
    schema_path: 'demos/go/pkg/subgraphs/products/subgraph/schema.graphqls'
    routing_url: 'https://products-default-${PR_NUMBER}.fly.dev/graphql'

  - name: 'hobbies'
    schema_path: 'demos/go/pkg/subgraphs/hobbies/subgraph/schema.graphqls'
    routing_url: 'https://hobbies-default-${PR_NUMBER}.fly.dev/graphql'
